#!/bin/bash

# SENTINEL APPLIANCE DEPLOYMENT SCRIPT

echo What is the environment
read envInput
ENV=$envInput
echo environment is $envInput

echo What is the organization
read orgInput
ORG=$orgInput
echo organization is $orgInput

echo What is the mssp
read msspInput
MSSP=$msspInput
echo mssp is $msspInput

echo What is your github username
read userInput
USER=$userInput
echo github username is $userInput

echo What is your github token
read tokenInput
TOKEN=$tokenInput
echo token is $tokenInput

# Variables
# This is where a Sensato employee will change these varibles per organization
# ENV="dev"
# ORG="ctoc"
# MSSP="ctoc"

# User access token generated by Brett Warrick (aka Renevant)
#TOKEN="c02f32574b7bbb6d3ff626cde0328aebedb6ca70"

sudo apt install software-properties-common -y
sudo apt-add-repository universe
sudo apt-add-repository multiverse

sudo apt update -y

sudo apt install curl python python-pip -y
pip install azure-cosmos

cd ~
git clone http://$USER:$TOKEN@github.com/Sensato/packer-nids.git
cd packer-nids
git checkout appliance

# Install Azure CLI
sudo apt install apt-transport-https lsb-release gnupg -y
curl -sL https://packages.microsoft.com/keys/microsoft.asc | \
    gpg --dearmor | \
    sudo tee /etc/apt/trusted.gpg.d/microsoft.asc.gpg > /dev/null
AZ_REPO=$(lsb_release -cs)
echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | \
    sudo tee /etc/apt/sources.list.d/azure-cli.list
sudo apt update -y
sudo apt install azure-cli -y

az extension add --name azure-cli-iot-ext

STR="Debug Message: Building Sentinel on environment $ENV, organization $ORG, msspid $MSSP."
echo $STR
sudo mkdir -p ~/.debug
sudo python build_sensor.py env=$ENV orgid=$ORG msspid=$MSSP buildos=linux > ~/.debug/packer-nids.debug-$(date +"%s").log 2>&1

# Self Destruct
# rm -rf ~/packer-nids
# sudo reboot
